### ISSUE TITLE
Question concerning copyrights

### ISSUE THREAD

**Issue by ghost** [ihmcrobotics/ihmc-soem-wrapper#4]
Hey :)
Now that I have the library working, I want to ask - I want to write my master's thesis at Sofia University in Bulgaria and use your library to make a demonstration with the hardware I have. Am I allowed to do that?xD
I will add NOTICE files and everything necessary to avoid plagiarism.
Thanks :)

**Comment by jespersmith** [comment]
IHMC EtherCAT master is licensed under the Apache 2.0 license. You're pretty much allowed to use it in open and closed source software as you see fit. 

For details, see https://github.com/ihmcrobotics/ihmc-ethercat-master/blob/master/license.txt. A notice would be appreciated, for more info see section 4. This mostly concerns copying and redistributing our code into your library. If you use it directly from Maven/Bintray a small note in the NOTICE file would be appreciated.

**Comment by ghost** [comment]
Awesome,thanks :)
